### ISSUE TITLE
Form references hidden class without properly including it for use

### ISSUE THREAD

**Issue by kczx3** [phpopenfw/phpOpenFW2#3]
The Form class should either mimic FormToo and manually create the input element inside the add_hidden method or add a 'use' statement `use \phpOpenFW\Form\Elements\hidden;`.

https://github.com/phpopenfw/phpOpenFW2/blob/8bea62726089594db6a3cf26d63dca316f4133e7/src/plugins/Form/Forms/Form.php#L471

**Comment by phpopenfw** [comment]
Fixed. Are you using this class instead of the FormToo class? If you are, I would suggest you use the FormToo class as it is newer and more versatile.

**Comment by kczx3** [comment]
Thanks.  I've used both.  The instance I found that was using this is in legacy code.  I can look at updating it later.  Much appreciated.
