### ISSUE TITLE
SQL Builder - hints

### ISSUE THREAD

**Issue by kczx3** [phpopenfw/phpOpenFW2#4]
Is the proper way to include a hint in a SQL query to use the SelectRaw method?

**Comment by phpopenfw** [comment]
Is the hint part of your SQL select statement? The SelectRaw method adds a line into the select columns part of a select statement without detecting a comma delimited list of columns.

**Comment by kczx3** [comment]
Yes, the standard placement for a query hint is right after the SELECT.

```sql
SELECT /*+ INDEX(O) */ order_id, encntr_id FROM ORDERS O
```

**Comment by phpopenfw** [comment]
That should work. Please re-post if it does not.
