### ISSUE TITLE
SSA not buffering output properly

### ISSUE THREAD

**Issue by kczx3** [phpopenfw/phpOpenFW2#5]
Should the ssa render method actually return parent::render($buffer) if $buffer is true?

https://github.com/phpopenfw/phpOpenFW2/blob/548dc649a6479afbbeb9d29bbfaa287976a3ee91/src/plugins/Form/Elements/ssa.php#L150

**Comment by phpopenfw** [comment]
Fixed and bundled in v2.2.1 release.

**Comment by kczx3** [comment]
Awesome, thank you!
