### ISSUE TITLE
LDAP Bind

### ISSUE THREAD

**Issue by kczx3** [phpopenfw/phpOpenFW2#6]
Is the LDAP::Bind method supposed to utilize the $user and $pass parameters at all?  Or if we want to bind with a different user/password then we should just instantiate a new LDAP object?

https://github.com/phpopenfw/phpOpenFW2/blob/9b3b8373c8e619cacf5b1fe89286950764072d18/src/plugins/Database/LDAP.php#L143

**Comment by kczx3** [comment]
I ended up just extending LDAP and implementing my own Bind method for now.

**Comment by phpopenfw** [comment]
Just fixed this issue in v2.2.2
