### ISSUE TITLE
SSV2 - is_empty_or_zero

### ISSUE THREAD

**Issue by kczx3** [phpopenfw/phpOpenFW2#7]
https://github.com/phpopenfw/phpOpenFW2/blob/f4935a27572abfc6f6020dff1224b913cd365804/src/plugins/Form/Validation/SSV2.php#L350

Should this expression instead be:

```php
$vr = ($var_val1 == '' || (string)$var_val1 == '0');
```

**Comment by phpopenfw** [comment]
Fixed.
