### ISSUE TITLE
Unnecessary check in get_mod_var

### ISSUE THREAD

**Issue by kczx3** [phpopenfw/phpOpenFW2#9]
https://github.com/phpopenfw/phpOpenFW2/blob/0b737e40e5b93957d4493985bb77ef72e6704a90/src/plugins/Framework/App/Flow/Module.php#L463

Is the second expression in this `if` statement a typo?  If the passed `$var_name` is truly set in `$_SESSION[$mod_index] then wouldn't `!empty($_SESSION[$mod_index])` always return true?  Perhaps that check should come first in the `if` statement although I think that `isset` guards against multiple levels of an array.

**Comment by cclark61** [comment]
Fixed! Sorry for the delay.

Christian Clark
http://www.christianclark.me/
616.821.2754

**Comment by kczx3** [comment]
No worries.  Thanks!
